algoritmo "VOLUME_CAIXA"
// Função :
// Autor :
// Data : 10/5/2017
// Seção de Declarações 
var
   v,c,l,a:real
inicio
//Pede ao usuário de que digite os valores de entrada
 escreval("Digite o comprimento da caixa:")
 leia(c)
 escreval("Digite a largura da caixa:")
 leia(l)
 escreval("Digite a altura da caixa")
 leia (a)
 //calcula o volume da caixa
 v<-c*a*l
 escreval("O volume da caixa é :", v)
fimalgoritmo
