algoritmo "semnome"
// Função :
// Autor :
// Data : 10/7/2017
// Seção de Declarações 
var
base,expoente,cont,res:real

inicio
escreva("Digite o valor da base : ")
leia(base)
escreva("Digite o valor do expoente: ")
leia (expoente)
cont<-1
res<-1
 enquanto cont<=expoente  faca
    res<-res*base
    cont<-cont+1
    escreva(base," ^",expoente," = ",res)
    escreval("")
 fimenquanto



fimalgoritmo
