algoritmo "DIVISIVEL_POR_4"
// Função :
// Autor :
// Data : 10/7/2017
// Seção de Declarações 
var
x,cont:inteiro
inicio
escreva("Digite um valor inteiro :")
leia(x)
cont<-1

se x mod 4=0 entao

   escreva("O número é divisivel por 4")
   escreval()
   enquanto x < 201 faca
      escreva(x)
      escreval(" ")
      x<-x+4
   fimenquanto
   senao
        escreva("O número não é divisivel por 4")

fimse

fimalgoritmo
