algoritmo "SOMA_DOS_QUADRADOS"
// Função :  Efetuar a soma dos quadrados de três valores
// Autor :
// Data : 10/5/2017
// Seção de Declarações 
var
 a,b,c,resultado:real
inicio
 escreval("Insira o primeiro valor")
 leia(a)
 escreval("Insira o segundo valor")
 leia(b)
 escreval("Insira o terceiro valor")
 leia(c)
 resultado<- ( exp(a,2)+ exp(b,2)+exp(c,2) )
 escreval("A soma do quadrado dos três valores é :",resultado)
 
 
fimalgoritmo
