algoritmo "semnome"
// Função :
// Autor :
// Data : 10/8/2017
// Seção de Declarações 
var
a,b: vetor[0..4] de real
i:inteiro
inicio
      escreval("Digite 5 valores para o grupo 'A' ")
           para i de 0 ate 4 passo 1 faca
           leia(a[i])
      fimpara
      escreval("Fatorial do grupo A ")
      para i de 0 ate 4 passo 1 faca
           b[i]<-a[i]

           escreval(b[i])
      fimpara
fimalgoritmo
